pipeline {

    agent any

    stages {

        stage('Checkout') {

            steps {

                echo "Teste de Hello Wordl!"

            }

        }

        stage('Grant key permission') {

            steps {

                sh "chmod 400 /home/ec2-user/keys/backend-key.pem"

            }

        }

        stage('Access backend EC2') {

            steps {

                sh """
                   ssh -o StrictHostKeyChecking=no -i /home/ec2-user/keys/backend-key.pem ec2-user@ec2-3-214-52-91.compute-1.amazonaws.com '"cd ~/ec2-user/repo/backend && sudo git fetch && sudo git pull"'
                """

            }

        }

    }

}