name: Deploy Backend Application

on:
    push:
      branches: [main]

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Setup Java
          uses: actions/setup-java@v3
          with:
            distribution: 'oracle'
            java-version: '17'
        - name: Build project
          run: mvn clean install -DskipTests
        - name: Login Docker Hub
          run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
        - name: Build docker image
          run: docker build -t ${{secrets.DOCKER_USERNAME}}/limpee_backend .
        - name: Push docker image
          run: docker push ${{secrets.DOCKER_USERNAME}}/limpee_backend